{{- $serv := "worker" -}}
{{- if .Values.deployWorker -}}
{{- $targetEnv := .Values.targetEnvironment -}}
{{- $envSettings := pluck $targetEnv .Values.environments | first -}}
{{- $servSettings := pluck $serv $envSettings | first -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "name" . }}-{{ $serv }}
  labels:
    app: {{ include "name" . }}-{{ $serv }}
    helm.sh/chart: {{ include "chart" . }}
    environment: {{ $targetEnv | default "production" | quote }}
    instance: {{.Release.Name }}
spec:
  progressDeadlineSeconds: 600
  # replica count should be dependent on the name of the deployment, if web / worker / beater
  replicas: {{ $servSettings.replicaCount }}
  # make sure we don't run out of storage
  revisionHistoryLimit: 10
  # 
  selector:
    matchLabels:
      app: {{ include "name" . }}-{{ $serv }}
      instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "name" . }}-{{ $serv }}
        instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "name" . }}-{{ $serv }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{  $envSettings.pullPolicy | quote }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        env:
          - name: SECRET_KEY
            value: "notsosecret"
          {{- if $servSettings.configMaps }}
          envFrom:
          {{- range $servSettings.configMaps }}
          - configMapRef:
              name: {{ . }}
          {{- end}}
          {{- end }}
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        resources:
          # TODO: move these under servSettings as different services running on this image can require different resources
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
{{- end -}}
